var mediaConfig = [
	{
		group: 'root',
		groupId: 'dionysos',
		title: 'Dionysos-Mosaik, Köln',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck.svg',
		sourceFile: 'rba_d022237.jpg',
		title: '🦆 Stockente',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-empty.svg',
		sourceFile: 'rba_d022237.jpg',
		title: '🦆 Stockente (in weiß)',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-frame.svg',
		sourceFile: 'rba_d022237.jpg',
		title: '🦆 Stockente mit Rahmen',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-frame-empty.svg',
		sourceFile: 'rba_d022237.jpg',
		title: '🦆 Stockente mit Rahmen (in weiß)',
	},
	{
		attribution: '',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: '',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/flower.svg',
		sourceFile: '',
		title: '🌼 Blume (noch in Arbeit)',
	},
	{
		group: 'root',
		groupId: 'kidsdigilab',
		title: 'kids.digilab.berlin',
	},
	{
		attribution: 'Deutsches Technikmuseum',
		group: 'kidsdigilab',
		license: 'OER / CC BY SA 4.0',
		path: 'media/raster-8x8-smiley.svg',
		sourceFile: 'raster-8x8-smiley.png',
		title: '😃 Smiley',
	},
	{
		attribution: 'Deutsches Technikmuseum',
		group: 'kidsdigilab',
		license: 'OER / CC BY SA 4.0',
		path: 'media/raster-12x12-pinguin.svg',
		sourceFile: 'raster-12x12-pinguin.png',
		title: '🐧 Pinguin',
	},
];
