var mediaConfig = [
	{
		group: 'root',
		groupId: 'savedimages',
		title: 'Letzte Kunstwerke',
	},
	{
		group: 'root',
		groupId: 'dionysos',
		title: 'Dionysos-Mosaik, Köln',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck.svg',
		sourceFile: 'rba_d022237.jpg',
		title: 'Stockente',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-empty.svg',
		sourceFile: 'rba_d022237.jpg',
		title: 'Stockente',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-frame.svg',
		sourceFile: 'rba_d022237.jpg',
		title: 'Stockente mit Rahmen',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/duck-frame-empty.svg',
		sourceFile: 'rba_d022237.jpg',
		title: 'Stockente mit Rahmen',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Michael Albers, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/flower.svg',
		sourceFile: 'rba_d035090.jpg',
		title: 'Blume',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Michael Albers, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/flower-empty.svg',
		sourceFile: 'rba_d035090.jpg',
		title: 'Blume',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/maenade.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Mänade mit Kithara (Saiteninstrument)',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/maenade-empty.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Mänade mit Kithara (Saiteninstrument)',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/satyr.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Satyr mit Doppelflöte',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/satyr-empty.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Satyr mit Doppelflöte',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/maenade-satyr.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Mänade mit Kithara (Saiteninstrument) und Satyr mit Doppelflöte',
	},
	{
		attribution: 'Rheinisches Bildarchiv Köln / Römisch Germanisches Museum Köln / Anja Wegner, bearbeitet',
		dating: 'ca. 220-355',
		group: 'dionysos',
		license: 'CC BY-SA 3.0 DE',
		material: 'Natursteine, Glas, Keramik',
		path: 'media/maenade-satyr-empty.svg',
		sourceFile: 'rba_d022240.jpg',
		title: 'Mänade mit Kithara (Saiteninstrument) und Satyr mit Doppelflöte',
	},
	{
		group: 'root',
		groupId: 'kidsdigilab',
		title: 'kids.digilab.berlin',
	},
	{
		attribution: 'Deutsches Technikmuseum, bearbeitet',
		group: 'kidsdigilab',
		license: 'OER / CC BY SA 4.0',
		path: 'media/raster-8x8-smiley.svg',
		sourceFile: 'raster-8x8-smiley.png',
		title: 'Smiley',
	},
	{
		attribution: 'Deutsches Technikmuseum, bearbeitet',
		group: 'kidsdigilab',
		license: 'OER / CC BY SA 4.0',
		path: 'media/raster-12x12-pinguin.svg',
		sourceFile: 'raster-12x12-pinguin.png',
		title: 'Pinguin',
	},
];
